apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
                  - containerPort: 3306
          env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "password"
        - name: test-rest
          image: test-rest:0.0.1
          volumeMounts:
                  - mountPath: /kube/txt
                    name: txt-volume
          imagePullPolicy: Never
          ports:
                  - containerPort: 8082
      volumes:
              - name: txt-volume
                hostPath:
                  path: /home/jun/docker/example_pod/pod_test/test_image/kube/txt
                  type: Directory
                    #        - name: text-write
                    #          image: juneda/text-write:0.0.1
                    #        - name: text-read
                    #          image: juneda/text-read:0.0.1
